### ISSUE TITLE
PyGMI crashes on double clicking connector line

### ISSUE THREAD

**Issue by cecgeology** [Patrick-Cole/pygmi#11]
Hi,
I'm just getting started exploring the features and I have come across something that seems to crash the program out every time (at least the times I have tried). I am using the 64 bit installer 3.1.0.0 version on windows 10.
After importing raster, I add some other function and join with a line. If I then double click the line the program crashes out. I've tried connecting various different things such as raster to smoothing, rtp, igrf, even equation to equation, and it crashes every time.
Is there more data/info I can dig up to help out on this?

**Comment by Patrick-Cole** [comment]
Hi,
Once the line connects the data import and then new function, you need to double click on the new function (not the line). Then a dialog should pop up relating to the new function.

I tested double clicking on the line, and it does crash. I will stop this from happening in the next release. 

Let me know if you are successful.

Patrick

**Comment by cecgeology** [comment]
Thanks. 
Yes, I did get how to use the formula, just wanted to report the bug, and it also seems to happen just single clicking.
Cris

**Comment by Patrick-Cole** [comment]
Hi,

My apologies, I misunderstood. I will check it out. 

Thanks for the report. 

Patrick

**Comment by Patrick-Cole** [comment]
Hi,

I have fixed this issue. 

Regards

Patrick
