### ISSUE TITLE
RTP with odd stripe results

### ISSUE THREAD

**Issue by cecgeology** [Patrick-Cole/pygmi#12]
Hi, 
In testing out the RTP function I double clicked on the Reduction to Pole box, chose the dataset, and entered inclination and declination.  The results are not comparing much to the one I derived from the Magpick software, and could not see figure out what code reference you were using based on reading the RTP code in dataprep.py. 
The most obvious error is data stripes in an E-W orientation that were not present in the original TMI data (nor in the Magpick generated RTP).
Here is an example:
![image](https://user-images.githubusercontent.com/19914461/82246778-505e3100-9913-11ea-9c98-ef13a0a50e27.png)
They are on the order of 300 m. In this area the data was collected on lines perpendicular to these RTP stripes, but in areas with lines in east west they are also present (thus I am ruling out a data collection artifact).
Not sure if related, but if I reopen the RTP function it reverts to -62.50, -16.75, this might be handy to remember what was entered previously (if only to check that the values were correct)
Sort of along these lines, and since I see you have a lot of code by Cooper, any chance you have his "Differential reduction to the pole" code? I found the matlab version right before coming across PyGMI.
Regards and thanks for your other quick responses, 
Cris

**Comment by Patrick-Cole** [comment]
Hi,

I use the following formula applied in the frequency domain: 
filt = 1/(np.sin(I)+1j*np.cos(I)*np.cos(D-alpha))**2

The reference that I found is: Macleod, I.N., Jones, K., Dai, T.F., 1993. 3-D analytic signal in the interpretation of total magnetic field data at low magnetic latitudes. Exploration Geophysics 24, 679–688.

It is possible that there is a bug somewhere. Can you let me know your inclination and declination so that I can model something to test with? 

Also, I will check out the resetting of inclination and declination to -62.5 and -16.75

I haven't done 'Differential reduction to the pole' but I can check it out. 

Thanks!

**Comment by cecgeology** [comment]
Awesome, thanks. 
I am using 57.2 and 5 for inclination/declination.
Just for fun, I tested several values of inclination (both positive and negative), including reversing I/D and got those stripes consistently (except for 0 and 90 as you would expect). 
I also tested a nearby, different dataset and get the same effect.
I have been using surfer grids for the input, but I also converted to ermapper format. I also converted it so that it would have square cell sizes (the surfer grid is 8 cm different in X-Y) but those all gave the same results. 
Hope that helps

**Comment by Patrick-Cole** [comment]
Hi,
I checked everything out and verified the problem. I have fixed it and changed the FFT formula to one referred to by Cooper: 

filt = 1/(np.sin(I)+1j*np.cos(I)*np.sin(D+alpha))**2

I have also added a Tukey taper to the data before FFT.

The results seem fine to me now. I have updated the git repository. Are you able to check using that? If you download the new source code you should be able to just replace the files in your pygmi directory and run it again.

Let me know if this helps

Patrick

**Comment by cecgeology** [comment]
Thanks, 
I replaced all the files and reran the program I try to do the RTP it starts (and asks for dec/inc) but after I click OK it crashed out the program. Reinstalled (with installer and works fine) and tried again but crashed it out. Not sure how I can debug this, and other filters and functions work.

**Comment by Patrick-Cole** [comment]
Hi,

Is it possible to get a copy of the data you are using? (with coordinates changed of course). I just want to make sure I have not missed anything. I can then place an installer on github.

If so, you can email it to pcole@geoscience.org.za. 

Regards

Patrick

**Comment by cecgeology** [comment]
Looks like the RTP now gives the expected results.
