### ISSUE TITLE
Closed immediately

### ISSUE THREAD

**Issue by abdulhafidz6** [Patrick-Cole/pygmi#13]
Hi.. Thanks for this impressive software!!!

I've just installed this software and tried to follow the Quick start example flow. I used a DEM data (aster gdem) for Raster Input and selected Smoothing tool, put the connector line, and right click on "Smoothing". When I pressed OK, then the program closed immediately without error notification. How can I fix this issue?

In my issue, I use the windows installer 3.2.1.1 on Windows 10 Enterprise version 2004
I tried to install trough python, all libraries had installed before, but when installing "pygmi", it can't be going further due to discretize installation package had error. 

Thank you

**Comment by Patrick-Cole** [comment]
Hi, 

Thanks for the feedback, sorry about the I will see if I can duplicate it on my side. If you wish to install through python on windows (just to get an error message), then I recommend getting discretize from : https://www.lfd.uci.edu/~gohlke/pythonlibs/

You should be able to get almost all the libraries from this site. Importantly, they are pre-built so they will install neatly with pip.

Regards

Patrick
