### ISSUE TITLE
Bug: Reduction To The Pole Feature

### ISSUE THREAD

**Issue by KerinPithawala** [Patrick-Cole/pygmi#14]
I have used several values for Inclination of Magnetic Field and Declination of Magnetic Field for my raster data however, I did not get proper output. 
Grid Image:
![image](https://user-images.githubusercontent.com/46436993/121907853-13e54a80-cd4a-11eb-83dc-26a8845d4cde.png)

RTP Output Image:
![image](https://user-images.githubusercontent.com/46436993/121906916-34f96b80-cd49-11eb-9c74-ae568a4176ae.png)

**Comment by Patrick-Cole** [comment]
Hi,

Can you send me the your data and the inclination and declination you used? I can then see if I can find the problem.

Thanks for letting me know

Regards,

Dr Patrick Cole
Geophysicist
Geophysics and Remote Sensing
Tel: +27 (0)12 841 1524
Email: ***@***.******@***.***> |  Website: http://www.geoscience.org.za<http://www.geoscience.org.za/>
280 Pretoria Street, Silverton, Pretoria, South Africa, 0184
Private Bag X112, Pretoria, South Africa, 0001

***@***.***D44366.7EE885C0]

***@***.***D44366.7EE885C0]

This message is subject to the CGS’s copyright terms and conditions, e-mail legal notice, and implemented Open Document Format (ODF) standard. The full disclaimer details can be found at CGS Disclaimer.<https://www.geoscience.org.za/index.php/legal> Please consider the environment before printing this email.



From: Kerin Pithawala ***@***.***>
Sent: Monday, 14 June 2021 16:23
To: Patrick-Cole/pygmi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Patrick-Cole/pygmi] Bug: Reduction To The Pole Feature (#14)


I have used several values for Inclination of Magnetic Field and Declination of Magnetic Field for my raster data however, I did not get proper output.
Grid Image:
[image]<https://user-images.githubusercontent.com/46436993/121907853-13e54a80-cd4a-11eb-83dc-26a8845d4cde.png>

RTP Output Image:
[image]<https://user-images.githubusercontent.com/46436993/121906916-34f96b80-cd49-11eb-9c74-ae568a4176ae.png>

**Comment by KerinPithawala** [comment]
Inclination of Magnetic Field: 80.00
 Declination of Magnetic Field: 0.00

**Comment by Patrick-Cole** [comment]
On my side it seems to work. Can you (if possible) email me the data at pcole@geoscience.org.za? Assuming it is  not too big of course. I want to check to see if there is anything in your data triggering the error.

**Comment by KerinPithawala** [comment]
I will send an email with the data. Thanks.

**Comment by KerinPithawala** [comment]
The code is working perfectly. Thanks!
