### ISSUE TITLE
bin directory required for occam1dcsem executable

### ISSUE THREAD

**Issue by todowede** [Patrick-Cole/pygmi#16]
Hi @Patrick-Cole, thank you so much for your code. i find it very useful. I have a little issue. I have compiled OCCAM1DCSEM for my Ubuntu system and installed pygmi with `pip install pygmi`.  When i tried to run MT inversion, the code require me to place the OCCAM1DCSEM executable in a "bin" directory. Could you advise which bin directory does it refer to. Thank you.

**Comment by Patrick-Cole** [comment]
Hi,
PyGMI is looking for an occam1d binary in the site-packages/pygmi/bin directory found in your python installation. I suspect this is not the best way to do this, and can look into another location if requested. Let me know if this helps.
