### ISSUE TITLE
program crashes on save model when  Raster>Equation Editor is present

### ISSUE THREAD

**Issue by cecgeology** [Patrick-Cole/pygmi#21]
I added equation editor to my model and upon trying to save the project it instantly crashed.
I tried it as a new instance with just a single raster input and the equation editor and same result. i also tried it with just the Equation Editor on in the project and I get the same crash with this Error message:

Latest Errors and Messages:
__version__ = '3.2.8.0'
Traceback (most recent call last):
  File "C:\Program Files\PyGMI\pygmi\main.py", line 1102, in save
    item.my_class.saveproj()
  File "C:\Program Files\PyGMI\pygmi\raster\equation_editor.py", line 470, in saveproj
    self.saveobj(self.textbrowser)
  File "C:\Program Files\PyGMI\pygmi\misc.py", line 297, in saveobj
    self.projdata[otxt] = obj.plainText()
                          ^^^^^^^^^^^^^
AttributeError: 'QTextEdit' object has no attribute 'plainText'. Did you mean: 'toPlainText'

**Comment by cecgeology** [comment]
I modified 
File "C:\Program Files\PyGMI\pygmi\misc.py", line 297, in saveobj
self.projdata[otxt] = obj.plainText() 

as suggested by the error message to :
self.projdata[otxt] = obj.toPlainText() 
and the program does not crash and I can successfully save the project

**Comment by Patrick-Cole** [comment]
Thanks for this, I have fixed it on my side, as well.
