### ISSUE TITLE
Feature request - save a session

### ISSUE THREAD

**Issue by Murray2015** [Patrick-Cole/pygmi#8]
Hi, 

I'd like to request the ability to save a session to continue working at a later date - I have had pygmi crash a number of times and starting from scratch each time can be frustrating :)

**Comment by Patrick-Cole** [comment]
Hi,

You make a good point. Its something I have been meaning to do for a while. I will look into adding it.

Thanks for your feedback.

Patrick

**Comment by cecgeology** [comment]
This would be great, especially when the workflow is more than 2 or three operations. I would like to add it might be nice to make the session human readable so that for example the same flow could be applied to different datasets by simply searching and replacing in a text file.

**Comment by Patrick-Cole** [comment]
Hi, 

I have finally done this. You can check it out on the latest release.

Patrick
